# Atividade de Pandas -
#### Conteúdo: 
- Series

In [1]:
import numpy as np
import pandas as pd
import random

**1) Crie uma Series com o nome de cinco pessoas que você conhece, onde o index é a idade dessas pessoas**

In [17]:
pessoas = pd.Series(['Ana', 'Natan', 'Daniele', 'Daiane', 'Jose'], index = [20, 34, 46, 30, 5])
pessoas


20        Ana
34      Natan
46    Daniele
30     Daiane
5        Jose
dtype: object

**2) Escreva um programa que irá converter um Numpy Array para uma Series**

In [21]:
from numpy import random
random.seed(5)
random.randint(100, size=(3, 5))
data_array = random.randint(100, size=(4, 3))

print("NumPy Data Array is:")
print(data_array)

print("")

data_df = pd.DataFrame(data_array)
print("The DataFrame generated from the NumPy array is:")
print(data_df)

NumPy Data Array is:
[[27 44 77]
 [75 65 47]
 [30 84 86]
 [18  9 41]]

The DataFrame generated from the NumPy array is:
    0   1   2
0  27  44  77
1  75  65  47
2  30  84  86
3  18   9  41


**3) Escreva um programa que irá converter uma Series para um array**

In [24]:
pessoas = pd.Series(['Ana', 'Natan', 'Daniele', 'Daiane', 'Jose'], index = [20, 34, 46, 30, 5])
array = np.array(pessoas.index.values)
print(array)

[20 34 46 30  5]


**4) Implemente uma programa usando Python que cálcula a idade média, o desvio padrão, o somatório, os valores máximo e mínimos de uma series**

In [36]:
s = pd.Series([0, 5, 6, 14, 20, 25, 2, 50, 30, 9])

In [37]:
s.describe()

count    10.000000
mean     16.100000
std      15.545274
min       0.000000
25%       5.250000
50%      11.500000
75%      23.750000
max      50.000000
dtype: float64

In [38]:
print('soma dos valores ', sum(s))

soma dos valores  161


**5) Escreva um programa que irá ordenar uma Series**

In [39]:
s.sort_values(ascending=False)

7    50
8    30
5    25
4    20
3    14
9     9
2     6
1     5
6     2
0     0
dtype: int64